### ISSUE TITLE
should we delete this repo?

### ISSUE THREAD

**Issue by SimonCropp** [kijanawoodard/NServiceBus.SimpleInjector#2]
since we have this https://github.com/WilliamBZA/NServicebus.SimpleInjector  ?

**Comment by kijanawoodard** [comment]
I'd say this repo is certainly stale. :-D

**Comment by SimonCropp** [comment]
Would u mind deleting it to help with the google foo?

**Comment by kijanawoodard** [comment]
going going gone.
[shocked it's showing up in google]
